version: "3"

services:
  redis: 
     image: redislabs/redismod
     ports:
       - '6379:6379' 
  
  app-redis:
    build:
      context: .
      dockerfile: Dockerfile.app_redis
    depends_on:
      - redis
    ports:
      - '8000:80'

# docker-compose --file docker-compose-redis.yml up
# curl localhost:8000