# 
FROM python:3.9

# 
WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./app_celery_redis_sqlite /code/app

# 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]

# docker build -t app_redis_celery_sqlite . -f Dockerfile.app_redis_celery_sqlite
# docker run -d --name sqldbimage_c1 sqldbimage 
# docker start --name sqldbimage_c1 (retains memory of database)
