version: "3"

services:
  redis: 
     image: redislabs/redismod
     ports:
       - '6379:6379' 
  
  poc_filewatcher:
    build:
      context: .
      dockerfile: Dockerfile.poc_filewatcher
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - /tmp:/source_folder
    depends_on:
      - poc_worker1
      - poc_worker2


  poc_worker1:
    build:
      context: .
      dockerfile: Dockerfile.poc_worker1
    command: celery --app=poc_worker1.celery worker --loglevel=info --queues stage1_Queue
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    working_dir: /code/app
    depends_on:
      - redis

  poc_worker2:
    build:
      context: .
      dockerfile: Dockerfile.poc_worker2
    command: celery --app=poc_worker2.celery worker --loglevel=info --queues stage2_Queue
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    working_dir: /code/app
    depends_on:
      - redis

  poc_beat:
    build:
      context: .
      dockerfile: Dockerfile.poc_worker1
    command: celery --app=poc_worker1.celery beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    working_dir: /code/app
    depends_on:
      - redis

  poc_flower:
    build:
      context: .
      dockerfile: Dockerfile.poc_flower
    command: celery flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - 5555:5555
      # now go to it http://localhost:5555/
    depends_on:
      - redis
# docker-compose --file docker-compose-celery-redis2.yml up
# docker-compose --file docker-compose-celery-redis2.yml down
